config/routes.rb
Carcontrol::Application.routes.draw do


  resources :contatos

  get "clientes/index"

  # resources :cegonhas
  get "cars/new"
  get "search/index"
  get "cars/inativos"
  get "cars/editar_localizacao"

  resources :compradores
  resources :empresas
  resources :cars do
    get :limited_edit
  end

  resources :cegonhas do
    member do
      get :logistica
      post :logistica_save
    end
  end

  resources :parceiros
  devise_for :users, :path_prefix => "d"
  resources :users
  resources :clientes
  resources :financeiros
  match ":controller(/:action(/:id))(.:format)"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  root :to => 'clientes#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that"s not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ":controller(/:action(/:id))(.:format)"
end

app/controllers/compradores_controller.rb
class CompradoresController < ApplicationController
  # GET /compradores
  # GET /compradores.json
  before_filter :authenticate_user!

  def index
    @compradores = Comprador.all
    @empresas = Empresa.all
    @compradores.empty? ? @mensagem_compradores = "Nenhum Cliente Cadastrado" : @mensagem_compradores = "Clientes Cadastrados"
    @empresas.empty? ? @mensagem_empresas = "Nenhuma Empresa Cadastrada" : @mensagem_empresas = "Empresas Cadastradas"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @compradores }
    end
  end

  # GET /compradores/1
  # GET /compradores/1.json
  def show
    @comprador = Comprador.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comprador }
    end
  end

  # GET /compradores/new
  # GET /compradores/new.json
  def new
    @comprador = Comprador.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comprador }
    end
  end

  # GET /compradores/1/edit
  def edit
    @comprador = Comprador.find(params[:id])
  end

  # POST /compradores
  # POST /compradores.json
  def create
    @comprador = Comprador.new(params[:comprador])

    respond_to do |format|
      if @comprador.save
        format.html { redirect_to @comprador, notice: 'Comprador was successfully created.' }
        format.json { render json: @comprador, status: :created, location: @comprador }
      else
        format.html { render action: "new" }
        format.json { render json: @comprador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /compradores/1
  # PUT /compradores/1.json
  def update
    @comprador = Comprador.find(params[:id])
    # ajusta o valor da string do valor do pagamento pra bigdecimal

    if params[:comprador][:pagamentos_attributes]
      respond_to do |format|
        if @comprador.update_attributes(params[:comprador])
          # redireciona para o financeiros ao efetuar novo pagamento. Separa por cliente ou empresa
          if defined?(@comprador.cnpj)
            format.html { redirect_to :controller => :financeiros, :action => :show, :comprador_cnpj => @comprador.cnpj }
          elsif defined?(@comprador.cpf)
            format.html { redirect_to :controller => :financeiros, :action => :show, :comprador_cpf => @comprador.cpf }
          end
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @comprador.errors, status: :unprocessable_entity }
        end
      end
    else

    respond_to do |format|
      if @comprador.update_attributes(params[:comprador])
        format.html { redirect_to compradores_url, notice: 'Dados do Cliente atualizados com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comprador.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # DELETE /compradores/1
  # DELETE /compradores/1.json
  def destroy
    @comprador = Comprador.find(params[:id])
    @comprador.destroy

    respond_to do |format|
      format.html { redirect_to compradores_url }
      format.json { head :no_content }
    end
  end
end

app/views/compradores/_form.html.haml
- compradores = Comprador.all

= form_for(@comprador) do |f|
  - if @comprador.errors.any?
    .error_explanation
      %h2
        = "#{pluralize(@comprador.errors.count, "error")} prohibited this comprador from being saved:"
      %ul
        - @comprador.errors.full_messages.each do |msg|
          %li
            = msg
  .row
    .large-6.end
      %fieldset
        %legend
          %h5{ :style => "font-size: 1.3em" }
            Dados do Cliente
        .row
          .large-6.columns
            = f.label :nome, "Nome do Cliente"
            = f.text_field :nome, :id => "comprador_nome" 
          .large-6.columns
            = f.label :email, "E-Mail"
            = f.text_field :email, :id => "comprador_email"
        .row
          .large-6.columns
            = f.label :rg
            = f.text_field :rg, :id => "comprador_rg"
          .large-6.columns
            = f.label :cpf
            = f.text_field :cpf, :onkeyup =>"mascara(this,cpf); fillFieldsComprador(this)",:maxlength=>"14", :size => '30' , :id => 'comprador_cpf'
        .row
          .large-6.columns
            = f.label :telefone
            = f.text_field :telefone, :onkeyup => "mascara(this,telefone)", :maxlength => "14", :size => '30' , :id => 'comprador_telefone'
          .large-6.columns  
            = f.label :celular
            = f.text_field :celular, :onkeyup => "mascara(this,telefone)", :maxlength => "14", :size => '30' , :id => 'comprador_celular'
        .row
          .large-6.columns
            = f.label :parente, "Parente ou Conhecido do Cliente"
            = f.text_field :parente, :id => 'comprador_parente'
          .large-6.columns
            = f.label :telefone_parente, "Telefone do Parente ou Conhecido do Cliente"
            = f.text_field :telefone_parente, :onkeyup =>"mascara(this,telefone)", :maxlength=>"15", :size => '30' , :id => 'comprador_telefone_parente'
          
        = f.label :observacao, "Observação"
        = f.text_area :observacao, :cols => 40, :rows => 7

      = f.submit "Salvar", :class => 'button'

app/views/compradores/edit.html.haml
%p
  %h1 Editando Cliente

= render 'form'

app/views/compradores/index.html.haml
%p
  %h1= @mensagem_compradores
- if !@compradores.blank?
  .row
    %div{ :class => "large-12 columns" }
      %table#compradores.display{ :cellpading => 0, :cellspacing => 0, :border => 0, :width => '100%'}
        %thead
          %tr
            %th
              Nome
            %th
              Email
            %th
              RG
            %th
              CPF
            %th
              Telefone
            %th
              Carros Ativos
            %th
              Valor Pago Total
            %th
              Saldo Devedor

        %tbody
          - @compradores.each do |comprador|
            %tr
              %td
                = link_to comprador.nome, comprador
                = link_to image_tag("edit_local.png", :border=>0),edit_comprador_path(comprador, :comprador => comprador.id), :class => 'right'
              %td
                = comprador.email
              %td
                = comprador.rg
              %td
                = comprador.cpf
              %td
                = comprador.telefone
              %td
                = carros_ativos_do_cliente(comprador).html_safe
              %td
                = number_to_currency(soma_dos_pagamentos_efetuados(comprador))
              %td
                = number_to_currency(saldo_devedor_do_cliente(comprador))

%p
  %h1= @mensagem_empresas
- if !@empresas.blank?
  .row
    %div{ :class => "large-12 columns" }
      %table#empresas.display{ :cellpading => 0, :cellspacing => 0, :border => 0, :width => '100%'}
        %thead
          %tr
            %th
              Nome
            %th
              Email
            %th
              CNPJ
            %th
              Telefone
            %th
              Celular
            %th
              Carros Ativos
            %th
              Valor Pago Total
            %th
              Saldo Devedor
        %tbody
          - @empresas.each do |empresa|
            %tr
              %td
                = link_to empresa.nome, empresa
                = link_to image_tag("edit_local.png", :border=>0), edit_empresa_path(empresa, :empresa => empresa.id), :class => 'right'
              %td
                = empresa.email
              %td
                = empresa.cnpj
              %td
                = empresa.telefone
              %td
                = empresa.celular
              %td
                = carros_ativos_do_cliente(empresa).html_safe
              %td
                = number_to_currency(soma_dos_pagamentos_efetuados(empresa))
              %td
                = number_to_currency(saldo_devedor_do_cliente(empresa))

app/views/compradores/new.html.haml
%h1
  New comprador

= render 'form'

app/views/compradores/show.html.haml
.row
  .large-4.columns
    %table{ :cellspacing => "0", :summary => "Detalhes do Cliente"}
      %caption
        %h5
          Detalhes do Cliente
      %tr
        %th{ :style => "width:180px "}
          Nome do Cliente
        %td
          = @comprador.nome 
      %tr
        %th
          RG
        %td
          = @comprador.rg
      %tr
        %th
          CPF
        %td
          = @comprador.cpf
      %tr
        %th
          Telefone
        %td
          = @comprador.telefone
      %tr
        %th
          Celular
        %td
          = @comprador.celular
      %tr
        %th
          E-Mail
        %td
          = @comprador.email
      %tr
        %th
          Nome de Parente <br> ou Conhecido
        %td
          = @comprador.parente
      %tr
        %th
          Telefone de Parente <br> ou Conhecido
        %td
          = @comprador.telefone_parente
      %tr
        %th{ :style => "height:50px" }
          Observação
        %td
          = @comprador.observacao
  .large-4.columns 
    %table{ :cellspacing => "0", :summary => "Detalhes dos Carros" }
      %caption
        %h5
          Detalhes dos Carros
      %tr
        %th{ :style => "width:130px" }
          Carros Ativos
        %td
          = carros_ativos_do_cliente(@comprador).html_safe
      %tr
        %th
          Frete Total dos <br> Carros Ativos
        %td
          = number_to_currency(frete_total_do_cliente(@comprador)) 
      %tr
        %th
          Pagamento Total <br> Efetuado
        %td
          = number_to_currency(soma_dos_pagamentos_efetuados(@comprador)) 
      %tr
        %th
          Saldo Devedor
        %td
          = number_to_currency(saldo_devedor_do_cliente(@comprador)) 
      %tr
        %th{ :style => "height:50px" }
          Observação
        %td
          = @observacao
  .large-4.columns.end
    %table{ :cellspacing => "0", :summary => "Detalhes do Pagamento" }
      %caption
        %h5
          Detalhes dos Pagamentos
      %tr
        %th{:width => '50px'}
          Data do <br>Pagamento
        %th
          Valor do <br> Pagamento
        %th
          Forma de <br> Pagamento
        %th
          Saldo
      

      - @comprador ? owner = @comprador : owner = @empresa
      - owner.pagamentos.each do |pagamento|
        - if pagamento.saldo >= 0
          - row_class  = 'blue'
        - else
          - row_class = 'red'
        %tr
          %td
            = pagamento.data_pagamento.strftime('%d/%m/%Y') unless pagamento.data_pagamento.nil?
          %td
            = number_to_currency(pagamento.valor)
          %td
            = pagamento.forma_pagamento
          %td{ :class => row_class }
            = number_to_currency(pagamento.saldo)
      
= link_to 'Editar', edit_comprador_path(@comprador), :class => :button
= link_to 'Voltar', compradores_path, :class => :button