config/routes.rb
Carcontrol::Application.routes.draw do


  resources :contatos

  get "clientes/index"

  # resources :cegonhas
  get "cars/new"
  get "search/index"
  get "cars/inativos"
  get "cars/editar_localizacao"

  resources :compradores
  resources :empresas
  resources :cars do
    get :limited_edit
  end

  resources :cegonhas do
    member do
      get :logistica
      post :logistica_save
    end
  end

  resources :parceiros
  devise_for :users, :path_prefix => "d"
  resources :users
  resources :clientes
  resources :financeiros
  match ":controller(/:action(/:id))(.:format)"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  root :to => 'clientes#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that"s not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ":controller(/:action(/:id))(.:format)"
end

app/models/parceiro.rb
class Parceiro < ActiveRecord::Base
  attr_accessible :carros, :celular, :cidade_destino, :cidade_id, :cidade_origem, :observacao, :contato,
  		:estado_destino, :estado_id, :estado_origem, :localizacao, :nome, :telefone, :cnpj, :email, :cpf,
      :pagamentos_attributes, :debitos_attributes

  has_many :debitos, :through => :cars
  has_many :cars
  has_many :historicos
  has_many :pagamentos
  has_many :compradores
  has_many :empresas


  accepts_nested_attributes_for :cars, :pagamentos, :compradores, :debitos

  validates	:nome, :presence => { :message => "- O nome nao pode ser deixada em branco!" }

  before_save :capitaliza_nome
  after_update :activate_cars

  def capitaliza_nome
    if self.nome
      self.nome = self.nome.titleize
    end
  end

  def active_cars
    self.cars.reject {|c| c.ativo == VEHICLE_STATUS.index('DELIVERED')}
  end

  def total_freight
    self.cars.map {|car| BigDecimal.new(car.debito.valor_total.to_s)}.inject(0, &:+)
  end

  def total_redispatch_tax
    self.cars.map {|car| BigDecimal.new(car.debito.taxa_despacho.to_s)}.inject(0, &:+)
  end

  def activate_cars
    unless self.cars.nil?
      self.cars.each do |car|
        car.ativo = "#{VEHICLE_STATUS.index 'ON_TRANSIT'}"
        car.save
      end
    end
  end

  def clients
    self.cars.map(&:owner).uniq
  end

  def client_total_redispatch_taxes(client)
    cars = self.cars_from_client(client)
    cars.map {|car| BigDecimal.new(car.debito.taxa_despacho.to_s)}.inject(0, &:+)
  end

  def cars_from_client(client)
    self.cars.select {|c| c.owner == client}
  end
end

app/controllers/parceiros_controller.rb
class ParceirosController < ApplicationController
    before_filter :authenticate_user!

  def index
	@parceiros = Parceiro.all
    @parceiros.empty? ? @mensagem = "Nenhum Parceiro Cadastrado" : @mensagem = "Parceiros Cadastrados"
  end

  def new
    gon.parceiros = Parceiro.all
    @parceiro = Parceiro.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @parceiro }
    end
  end

  def create
    @parceiro = Parceiro.new(params[:parceiro])

	  respond_to do |format|
  	  if @parceiro.save
  	    format.html { redirect_to @parceiro, notice: 'Parceiro foi criada com sucesso.' }
  	    format.json { render json: @parceiro, status: :created, location: @parceiro }
  	  else
  	    format.html { render action: "new" }
  	    format.json { render json: @parceiro.errors, status: :unprocessable_entity }
  	  end
	  end
  end

  def show
  	@parceiro = Parceiro.find(params[:id])

    unless @parceiro.cars.nil?
      @cars_cpf = @parceiro.cars
      @cars_ativos = @parceiro.cars.reject {|c| c.ativo == 0}
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parceiro }
    end
  end


  def edit
    gon.parceiros = Parceiro.all
    @parceiro = Parceiro.find(params[:id])
  end

  def update
    @parceiro = Parceiro.find(params[:id])

    respond_to do |format|
      if @parceiro.update_attributes(params[:parceiro])

        if params[:editar_localizacao]
          flash[:notice] = 'Dados atualizados com sucesso!'
          redirect_to :action => :edit, :parceiro => @parceiro, :editar_localizacao => true  and return
        else
          format.html { redirect_to @parceiro, notice: 'Dados do parceiro atualizados com sucesso.' }
          format.json { head :no_content }
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @parceiro.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/parceiros_helper.rb
module ParceirosHelper
 def carros_com_parceiro(parceiro)
    frase = "Nenhum Carro com Parceiro."
    unless parceiro.cars.count.nil?
      if parceiro.cars.count > 0
        frase = "#{pluralize(parceiro.cars.count, 'carro')}: "
      end 
      parceiro.cars.each do |car|
      frase = frase + link_to(car.placa, car)
      parceiro.cars.last == car ? frase = frase + '.' :frase = frase + ', '
      end
    end
    return frase
  end

end

app/views/parceiros/_cars.html.haml
%table{ :class => "table_financeiros", :cellspacing => "0", :summary => "Carros Ativos" }
  %tr
    %th{ :width => '30'}
      Data de Compra
    %th{ :width => '140'}
      Modelo e Placa
    %th{ :width => '180'}
      Origem
    %th{ :width => '180'}
      Destino
    %th{ :width => '60'}
      Frete
    %th{ :width => '60'}
      Taxa de Plataforma
    %th{ :width => '60'}
      Taxa de Plataforma Origem
    %th{ :width => '60'}
      Taxa de Plataforma Destino
    %th{ :width => '60'}
      Taxa de Balsa
    %th{ :width => '60'}
      Taxa de Redespacho
    %th{ :width => '60'}
      Desconto
    %th{ :width => '60'}
      Valor Pago
    %th{ :width => '60'}
      Saldo Devedor
    %th{ :width => '60'}
      Data de Pagamento
  - carros.each do |car|
    - if car.status_pagamento.value == 1
      - @row_class = 'nao-pago'
    - elsif car.status_pagamento.value == 2
      - @row_class = 'pendente'
    - else
      - @row_class = '';

    %tr
      %td{ :class => @row_class }
        = car.data_compra.strftime("%d/%m")
      %td{ :class => @row_class }
        = link_to "#{car.modelo} - #{car.placa}", car
      %td{ :class => @row_class }
        - unless car.cidade_origem.nil?
          = Cidade.find(car.cidade_origem).text
          = Estado.find(car.estado_origem).sigla
      %td{ :class => @row_class }
        - unless car.cidade_destino.nil?
          = Cidade.find(car.cidade_destino).text
          = Estado.find(car.estado_destino).sigla
      %td{ :class => @row_class }
        = number_to_currency(car.debito.valor_frete)
      %td{ :class => @row_class }
        = number_to_currency(car.debito.taxa_plataforma)
      %td{ :class => @row_class }
        = number_to_currency(car.debito.taxa_plataforma_origem)
      %td{ :class => @row_class }
        = number_to_currency(car.debito.taxa_plataforma_destino)
      %td{ :class => @row_class }
        = number_to_currency(car.debito.taxa_balsa)
      %td{ :class => @row_class }
        = number_to_currency(car.debito.taxa_despacho)
      %td{ :class => @row_class }
        = number_to_currency(car.debito.desconto)
      %td{ :class => @row_class }
        = number_to_currency(car.debito.valor_pago)
      %td{ :class => @row_class }
        = number_to_currency(car.debito.saldo_devedor)
      %td{ :class => @row_class }
        = car.debito.data_pagamento.strftime("%d/%m/%Y") unless car.debito.data_pagamento.nil?

= stylesheet_link_tag "default"

app/views/parceiros/_form.html.erb
<% parceiros = Parceiro.all %>

<% if !current_user.admin? %>
  Desculpe, você precisa ter direitos administrativos para visualizar esta página!

<% else %>

<%= javascript_include_tag :defaults %>

<%= form_for(@parceiro) do |f| %>
  <% if @parceiro.errors.any? %>
    <div id="error_explanation">
      <h1><%= pluralize(@parceiro.errors.count, "erro") %> impediram que a compra fosse salva:</h1>
      
      <ul>
      <% @parceiro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      
      </ul>
    </div>
  <% end %>
  <!-- dados do veículo -->

  <fieldset><legend><h5 style="font-size: 1.3em">Dados do Parceiro</h5></legend>
  
    <p>Escolha apenas entre CPF ou CNPJ, porém não ambos!</p>
    <div class="field" style = "float:left; padding-right:10px;">
      <%= f.label :cpf, "CPF* " %><br />
      <%= f.text_field :cpf, :onkeyup =>"mascara(this,cpf); fillFieldsParceiro(this)",:maxlength=>"14", :size => '30', :id => 'parceiro_cpf' %> 
    </div>

    <div class="field">
      <%= f.label :cnpj, "CNPJ*" %><br />
      <%= f.text_field :cnpj, :onkeyup =>"mascara(this,cnpj); fillFieldsParceiro(this)",:maxlength=>"18", :size => '30', :id => 'parceiro_cnpj' %> 
    </div>

    <div class="field" style = "float:left; padding-right:10px;">
      <%= f.label :nome %><br />
      <%= f.text_field :nome, :id => 'parceiro_nome' %> 
    </div>

    <div class="field">
      <%= f.label :email, "E-Mail" %><br />
      <%= f.text_field :email, :id => 'parceiro_email'  %>
    </div>


    <div class="field" style = "float:left; padding-right:10px;">
      <%= f.label :telefone %>*<br />
      <%= f.text_field :telefone, :onkeyup => "mascara(this,telefone)", :maxlength => "14", :size => '30', :id => 'parceiro_telefone' %> 
    </div>

    <div class="field">
      <%= f.label :celular %><br />
      <%= f.text_field :celular, :onkeyup =>"mascara(this,telefone)", :maxlength=>"15", :size => '30' , :id => 'parceiro_celular' %> 
    </div>

    <div class="field">
      <%= f.label :observacao, "Observação" %><br />
      <%= f.text_area :observacao, :cols => 40, :rows => 7, :id => 'parceiro_observacao'%> 
    </div>




</fieldset>
  <!-- fim dos dados do veículo -->  
  <br />
  <div class="actions">
      <%= f.submit "Salvar" %>
    <% end -%>
  </div>
<% end -%>

<!-- javascript & ruby -->
<%= javascript_include_tag :defaults %>

<script type = "text/javascript">

function fillFieldsParceiro(oSel)
{
  var oForm = oSel.form;
  
  switch (oSel.value)
  { 
    <% parceiros.each do |parceiro| %>
    case '<%= parceiro.cnpj %>':
      oForm.parceiro_nome.value='<%= parceiro.nome%>';
      oForm.parceiro_email.value='<%= parceiro.email%>';
      oForm.parceiro_telefone.value='<%= parceiro.telefone%>';
      oForm.parceiro_celular.value='<%= parceiro.celular%>';
      oForm.parceiro_observacao.value='<%= parceiro.observacao%>';
    break;
    
    <%end%>
    case '':
      oForm.parceiro_nome.value='';
      oForm.parceiro_email.value='';
      oForm.parceiro_telefone.value='';
      oForm.parceiro_celular.value='';
      oForm.parceiro_observacao.value='';
      break;
  }
}

</script>

app/views/parceiros/_form.html.haml
- if !current_user.admin?
  .alert-box.alert
    Desculpe, você precisa ter direitos administrativos para visualizar esta página!

- else
  = form_for(@parceiro) do |f|
    - if @parceiro.errors.any?
      .alert-box.alert
        %h1
          = "#{pluralize(@parceiro.errors.count, 'erro')} impediram que a compra fosse salva:"
        %ul
          - @parceiro.errors.full_messages.each do |msg|
            %li
              = msg
    .row
      .large-6.columns
        %fieldset
          %legend
            %h5
              Dados do Parceiro
          .row
            %p
              Escolha apenas entre CPF ou CNPJ, porém não ambos!
            .large-6.columns
              = f.label :cpf, "CPF* "
              = f.text_field :cpf, :onkeyup =>"mascara(this,cpf); fillFieldsParceiro(this)",:maxlength=>"14", :size => '30', :id => 'parceiro_cpf'
            .large-6.columns
              = f.label :cnpj, "CNPJ*"
              = f.text_field :cnpj, :onkeyup =>"mascara(this,cnpj); fillFieldsParceiro(this)",:maxlength=>"18", :size => '30', :id => 'parceiro_cnpj'

          = f.label :nome
          = f.text_field :nome, :id => 'parceiro_nome'

          = f.label :email, "E-Mail"
          = f.text_field :email, :id => 'parceiro_email'
          .row
            .large-6.columns
              = f.label 'telefone*'
              = f.text_field :telefone, :onkeyup => "mascara(this,telefone)", :maxlength => "14", :size => '30', :id => 'parceiro_telefone'
            .large-6.columns
              = f.label :celular
              = f.text_field :celular, :onkeyup =>"mascara(this,telefone)", :maxlength=>"15", :size => '30' , :id => 'parceiro_celular'

            = f.label :observacao, "Observação"
            = f.text_area :observacao, :cols => 40, :rows => 7, :id => 'parceiro_observacao'
      .large-6.columns
        %fieldset
          %legend
            %h5 Dados dos Carros
          - @parceiro.cars.each do |car|
            = f.fields_for :debitos, car do |builder|
              .row
                .large-3.columns.left
                  %p= link_to car.placa, '#', 'data-reveal-id' => :carModal
                  #carModal.reveal-modal{ 'data-reveal' => ''}
                    =render 'shared/car_show', :car => car
                .large-4.columns.text-left
                  = car.modelo
                .large-5.columns.left.end
                  = car.person_or_company_name
              .row
                .large-3.columns
                  = builder.label :taxa_despacho, "Redespacho", :class => :inline
                .large-9.columns
                  = builder.text_field :taxa_despacho, :onkeyup =>"moeda(this)", :style => "text-align: Right", :value =>  number_to_currency(car.debito.taxa_despacho, :format => "%u %n", :separator => ",", :delimiter => ".", :unit => ''), :placeholder => 'R$'
              %br

    = f.submit "Salvar", :class => :button

app/views/parceiros/_parceiros.html.erb
<div class="floating-left" width = "1000px">
<table id="parceiros" class="display">
  <thead><tr>
    <th width = "1px">Nº</th>
      <th width = "140px"> CPF/CNPJ</th>
      <th>Nome</th>
      <th>Contato</th>
      <th width = "100px">Telefone</th>
      <th >Carros</th>
      <th width = "120px">Frete Total<br>dos Carros</th>
      <% if current_user.admin? %>
          <th width = "120px">Ações</th>
      <% end -%>
    </tr>
    </thead>
<tbody><% x = 0%>

<% @parceiros.each_with_index do |parceiro, index| %>

  <tr>
    <td class = "<%= @row_class %>"> <%= index + 1 %>. </td>
    <td class = "<%= @row_class %>">
      <%= parceiro.cpf.empty? ? link_to(parceiro.cnpj, parceiro) : link_to(parceiro.cpf, parceiro) %>
    </td>
    <td class = "<%= @row_class %>"><%= parceiro.nome %> </td>
    <td class = "<%= @row_class %>"><%= parceiro.contato %> </td>
    <td class = "<%= @row_class %>"><%= parceiro.telefone %> </td>
    <td> <%= (carros_com_parceiro(parceiro)).html_safe %> </td>
    <td><%= number_to_currency(parceiro.total_freight) %></td>
    <% if current_user.admin? %>
    <td class = "<%= @row_class %>"><%= link_to image_tag("details.png", :border=>0, :mouseover => "details_black.png", :title => "Ver Detalhes"), parceiro %> &nbsp;
        <%= link_to image_tag("edit.png", :border=>0, :alt => "Editar", :mouseover => "edit_black.png", :title => "Editar Entrada"), edit_parceiro_path(parceiro) %> &nbsp;
        <%= link_to image_tag("delete-item.png", :border=>0, :mouseover => "delete-item_red.png", :title => "Apagar Entrada"), parceiro, confirm: 'Tem certeza que deseja apagar a venda? Esta ação é irreversível!', method: :delete %>
    <% end -%>

  </tr>
<% end %></tbody>
</table>
</div>

app/views/parceiros/_parceiros.html.haml
.row
  %div{ :class => "large-12 columns" }
    %table.display#parceiros{ :cellpading => 0, :cellspacing => 0, :border => 0, :style => "width: 100%;"}
      %thead
        %tr
          %th
            CPF/CNPJ
          %th
            Nome
          %th
            Contato
          %th
            Telefone
          %th 
            Carros
          %th
            Frete Total
          %th
            Taxa de Redespacho Total
          - if current_user.admin?
            %th{ :width => "130px"}
              Ações
      %tbody
        - @parceiros.each do |parceiro|
          %tr
            %td{ :class => @row_class}
              = parceiro.cpf.empty? ? link_to(parceiro.cnpj, parceiro) : link_to(parceiro.cpf, parceiro)
            %td{ :class => @row_class}
              = parceiro.nome
            %td{ :class => @row_class}
              = parceiro.contato
            %td{ :class => @row_class}
              = parceiro.telefone
            %td
              = (carros_com_parceiro(parceiro)).html_safe
            %td.nowrap
              = number_to_currency(parceiro.total_freight)
            %td.nowrap
              = number_to_currency(parceiro.total_redispatch_tax)

            - if current_user.admin?
              %td{ :class => "#{@row_class} nowrap"}
                = link_to image_tag("details.png", :border=>0, :mouseover => "details_black.png", :title => "Ver Detalhes"), parceiro;
                = link_to image_tag("edit.png", :border=>0, :alt => "Editar", :mouseover => "edit_black.png", :title => "Editar Entrada"), edit_parceiro_path(parceiro);
                = link_to image_tag("delete-item.png", :border=>0, :mouseover => "delete-item_red.png", :title => "Apagar Entrada"), parceiro, confirm: 'Tem certeza que deseja apagar a venda? Esta ação é irreversível!', method: :delete

app/views/parceiros/edit.html.erb
<p><h1>Editando Parceiro</h1></p>
  <%= render 'form' %>
<%= link_to 'Detalhes', @parceiro %> |
<%= link_to 'Voltar', parceiros_path %>

app/views/parceiros/edit.html.haml
%p
  %h1 Editando Parceiro

= render 'form' 

app/views/parceiros/index.html.erb
<p><h1><%= @mensagem %> </h1></p>
<% if !@parceiros.empty? %>

<%= render 'parceiros' %>

<br />

<% end -%>
<div style="clear: both;"></div>
<br>
<% if current_user.admin? %>
  <%= button('Adicionar Parceiro', new_parceiro_path)%>

<% end -%>

app/views/parceiros/index.html.haml
%p
  %h1= @mensagem
- if !@parceiros.empty? 
  = render 'parceiros' 

- if current_user.admin? 
  = link_to 'Adicionar Parceiro', new_parceiro_path, :class => :button

app/views/parceiros/new.html.erb
<p><h1>Adicionando Parceiro</h1></p>

<%= render 'form' %>

<%= link_to 'Voltar', parceiros_path %>

app/views/parceiros/new.html.haml
%p
  %h1 Adicionando Parceiro

= render 'form'

app/views/parceiros/show.html.erb
<p id="notice"><%= notice %></p>

<% unless @parceiro.nil? %>
<p><b><%= link_to 'GERAR DOCUMENTO PDF', :action => 'generate_pdf', :id => @parceiro.id %> </b></p>
<% end -%>

<div class = 'floating_box'>

<table id="mytable" cellspacing="0" summary="Detalhes da parceiro" style="width:450px">
  <caption><h5>Detalhes da parceiro</h5></caption>
  <tr>
    <% if !@parceiro.cpf.empty? %>
      <th style="width:150px">CPF do Parceiro</th>
      <td style='border-top: 1px solid #C1DAD7;'><%= @parceiro.cpf %> </td>
    <% else %>
      <th style="width:150px">CNPJ do Parceiro</th>
      <td style='border-top: 1px solid #C1DAD7;'><%= @parceiro.cnpj %> </td>
    <% end -%>
  </tr>



  <tr>
  	<th>Nome do Parceiro</th>
  	<td><%= @parceiro.nome %></td>
  </tr>

  <tr>
    <th>Carros com Parceiro</th>
    <td> <%= raw(carros_com_parceiro(@parceiro)).html_safe %></td>
  </tr>
  <tr>
    <th>Localização Atual</th>
    <td><%= @parceiro.localizacao %></td>
  </tr>
  <% unless @parceiro.cidade_origem.nil? && @parceiro.estado_origem.nil? %>
  <tr>
    <th>Origem</th>
    <td><%= Cidade.find(@parceiro.cidade_origem).text %>, <%= Estado.find(@parceiro.estado_origem).sigla %></td>
  </tr>
  <% end -%>
  <% unless @parceiro.cidade_origem.nil? && @parceiro.estado_origem.nil? %>
  <tr>
    <th>Destino</th>
    <td><%= Cidade.find(@parceiro.cidade_destino).text %>, <%= Estado.find(@parceiro.estado_destino).sigla %></td>
  </tr>
  <% end -%>
  <tr>
    <th style = "height:50px">Observação</th>
    <td><%= @parceiro.observacao %></td>
  </tr>
  <tr>
</table>

<table id="mytable" cellspacing="0" summary="Fretes" style="width:300px">
  <caption><h5>Transações Financeiras do Parceiro</h5> </caption>

  <tr>
    <th style="width:180px" class = 'begin'>Valor Total dos Fretes</th>
    <td style='border-top: 1px solid #C1DAD7;'> <%= number_to_currency(@valor_total) %> </td>
  </tr>

  <tr>
    <th class = 'begin'>Valor Total Pago</th>
    <td><%= number_to_currency(@valor_pago) %>  </td>
  </tr>

  <tr>
    <th class = 'begin'>Saldo Devedor Total</th>
    <td><%= number_to_currency(@saldo_devedor) %>  </td>
  </tr>

</table>

</div>

<div style="clear: both;"></div>

<% if !@cars_ativos.empty? %>
<p><b>CARROS ATIVOS</b></p>
  <%= render 'cars', :carros => @cars_ativos %>
<br />
<% else %>
<p><b>Este parceiro não possui carros ativos no momento. </b></p>
<% end -%>
<div style="clear: both;"></div>
  <% frete_total = 0
     saldo_devedor = 0
     @parceiro.historicos.each do |hist|
        frete_total = hist.car.debito.valor_total + frete_total

        saldo_devedor =  hist.car.debito.saldo_devedor + saldo_devedor
    end%>
  <table id="mytable" cellspacing="0" summary="Histórico da Cegonha" style="width:900px">
      <caption><p><b>HISTÓRICO</b></p>

        <p><%= "Frete Total: #{number_to_currency(frete_total)}, Saldo Devedor: #{number_to_currency(saldo_devedor)}" %> </p> </caption>

    <% if @parceiro.historicos.empty? %>
      <th style = "text-align:left;">Nenhum carro no histórico</th>
      </table>
    <% else -%>

    <tr>
      <th width = '1' class = 'none'>Nº</th>
      <th class = 'begin' >Placa</th>
      <th>Data de Entrada</th>
      <th>Cidade de Entrada</th>
      <th>Data de Saída</th>
      <th>Cidade de Saída</th>
    </tr>

    <% @parceiro.historicos.each_with_index do |historico, index| %>
    <tr>
      <td class = "none"> <%= index + 1 %>. </td>
      <td class='begin'><%= link_to(historico.car.placa, historico.car) unless historico.car.nil? %> </td>
      <td><%= historico.data_entrada.strftime("%d/%m/%Y") unless historico.data_entrada.nil? %> </td>
      <td><%= historico.localizacao_entrada %> </td>
      <td><%= historico.data_saida.strftime("%d/%m/%Y") unless historico.data_saida.nil? %> </td>
      <td><%= historico.localizacao_saida %> </td>
      </tr>
    <%end%>


  </table>
  <% end -%>

<div style="clear: both;"></div>

<%= button('Editar', edit_parceiro_path(@parceiro)) %>
<%= button('Voltar', parceiros_path) %>

app/views/parceiros/show.html.haml
- unless @parceiro.nil?
  %p
    %b= link_to 'GERAR DOCUMENTO PDF', :action => 'generate_pdf', :id => @parceiro.id

  .row{ 'data-equalizer' => ""}
    .large-3.columns
      %table.text-left{ :cellspacing => "0", :summary => "Detalhes da parceiro", 'data-equalizer-watch' => '', :width => "100%" }
        %caption
          %h4
            Detalhes da parceiro
        %tr
          - if !@parceiro.cpf.empty?
            %th{ :style => "width:150px"}
              CPF do Parceiro
            %td
              = @parceiro.cpf
          - else
            %th{ :style => "width:150px" }
              CNPJ do Parceiro
            %td
              = @parceiro.cnpj
        %tr
          %th
            Nome do Parceiro
          %td
            = @parceiro.nome
        %tr
          %th
            Carros com Parceiro
          %td
            = raw(carros_com_parceiro(@parceiro)).html_safe
        %tr
          %th
            Localização Atual
          %td
            = @parceiro.localizacao
        - unless @parceiro.cidade_origem.nil? && @parceiro.estado_origem.nil?
          %tr
            %th
              Origem
            %td
              = Cidade.find(@parceiro.cidade_origem).text
              = Estado.find(@parceiro.estado_origem).sigla
        - unless @parceiro.cidade_origem.nil? && @parceiro.estado_origem.nil?
          %tr
            %th
              Destino
            %td
              = Cidade.find(@parceiro.cidade_destino).text
              = Estado.find(@parceiro.estado_destino).sigla
        %tr
          %th
            Observação
          %td
            = @parceiro.observacao

    .large-4.columns
      %table.text-left{ :cellspacing => "0", :summary => "Fretes", 'data-equalizer-watch' => '', :width => "100%" }
        %caption
          %h4
            Detalhes dos Carros
        %tr
          %th Cliente
          %th Placa
          %th Redespacho
        - @parceiro.cars.each do |car|
          %tr
            %td= car.person_or_company_name
            %td
              = link_to car.placa, '#', 'data-reveal-id' => :carModal
              #carModal.reveal-modal{ 'data-reveal' => ''}
                =render 'shared/car_show', :car => car
            %td= number_to_currency(car.debito.taxa_despacho)
        %th
          Total
        %th
        %td
          %b= number_to_currency(@parceiro.total_redispatch_tax)

    .large-5.columns.end
      %table.text-left{ :cellspacing => "0", :summary => "Fretes", 'data-equalizer-watch' => '', :width => "100%" }
        %caption
          %h4
            Financeiros
        %tr
          %th Cliente
          %th Carros
          %th Saldo Devedor
          %th Redespacho Total
          %th Receber
        - @parceiro.clients.each do |client|
          %tr
            %td
              = client.nome
            %td
              = @parceiro.cars_from_client(client).map(&:placa).to_sentence
            %td.nowrap.red
              = number_to_currency saldo_devedor_do_cliente(client)
            %td.nowrap
              = number_to_currency @parceiro.client_total_redispatch_taxes(client)
            %td.nowrap
              = number_to_currency (saldo_devedor_do_cliente(client) + @parceiro.client_total_redispatch_taxes(client)) * -1

  - if !@cars_ativos.empty?
    %p
      %b CARROS ATIVOS
    = render 'cars', :carros => @cars_ativos

  - frete_total = 0
  - saldo_devedor = 0
  - @parceiro.historicos.each do |hist|
    - frete_total = hist.car.debito.valor_total + frete_total
    - saldo_devedor =  hist.car.debito.saldo_devedor + saldo_devedor
    %table{ :cellspacing => "0", :summary => "Histórico do Parceiro", :width => '100%' }
      %caption.text-left
        %b HISTÓRICO
        %p= "Frete Total: #{number_to_currency(frete_total)} | Saldo Devedor: #{number_to_currency(saldo_devedor)}"
      - if @parceiro.historicos.empty?
        %th.text-left
          Nenhum carro no histórico
      - else
        %tr
          %th.begin
            Placa
          %th
            Data de Entrada
          %th
            Cidade de Entrada
          %th
            Data de Saída
          %th
            Cidade de Saída
        - @parceiro.historicos.each do |historico|
          %tr
            %td
              = link_to(historico.car.placa, historico.car) unless historico.car.nil?
            %td
              = historico.data_entrada.strftime("%d/%m/%Y") unless historico.data_entrada.nil?
            %td
              = historico.localizacao_entrada
            %td
              = historico.data_saida.strftime("%d/%m/%Y") unless historico.data_saida.nil?
            %td
              = historico.localizacao_saida

  = link_to 'Editar', edit_parceiro_path(@parceiro), :class => :button
  = link_to 'Voltar', parceiros_path, :class => :button