config/routes.rb
Carcontrol::Application.routes.draw do


  resources :contatos

  get "clientes/index"

  # resources :cegonhas
  get "cars/new"
  get "search/index"
  get "cars/inativos"
  get "cars/editar_localizacao"

  resources :compradores
  resources :empresas
  resources :cars do
    get :limited_edit
  end

  resources :cegonhas do
    member do
      get :logistica
      post :logistica_save
    end
  end

  resources :parceiros
  devise_for :users, :path_prefix => "d"
  resources :users
  resources :clientes
  resources :financeiros
  match ":controller(/:action(/:id))(.:format)"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  root :to => 'clientes#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that"s not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ":controller(/:action(/:id))(.:format)"
end

app/models/car.rb
#encoding: UTF-8
class Car < ActiveRecord::Base
  attr_accessible :localizacao, :modelo, :placa, :rota_id, :status_pagamento_id, :ativo, :estado_id, :cidade_id, :data_compra,
        :data_prevista, :cegonha_id, :comprador_attributes, :empresa_attributes, :debito_attributes, :observacao, :parceiro_id,
        :pagamentos_attributes, :estado_origem, :cidade_origem, :estado_destino, :cidade_destino

  belongs_to :status_pagamento
  belongs_to :cegonha
  belongs_to :comprador
  belongs_to :empresa
  belongs_to :parceiro
  has_one :debito
  has_many :historicos
  has_many :pagamentos
  accepts_nested_attributes_for :comprador, :empresa, :debito, :parceiro, :pagamentos

  validates	:placa,
  			:presence => { :message => "- A placa não pode ser deixada em branco!" },
  			:uniqueness => { :message => "- A placa já existe no banco de dados. É necessário que ela seja única" }

  validates :modelo,
  			:presence => { :message => "- O modelo do carro não pode ser deixado em branco!" }

  validates :status_pagamento_id, :car_not_paid => true

  before_save :license_plate_uppercase, :car_model_downcase, :remove_from_carrier_if_delivered,
    :person_or_company_name
  after_save :save_current_location
  after_find :titleize_model, :check_payments
  before_update :remove_car_from_freighter_tracking
  after_update :if_in_freighter_get_its_location, :add_car_to_freighter_tracking

  def person_or_company_name
    self.comprador.try(:nome) || self.empresa.try(:nome)
  end

  def remove_from_carrier_if_delivered
    if self.is_delivered?
      self.cegonha = nil
    end
  end

  def license_plate_uppercase
  	self.placa.upcase!
  end

  def car_model_downcase
  	self.modelo.downcase!
  end

  def titleize_model
  	self.modelo = self.modelo.titleize
  end

  def check_payments
    if self.pagamentos.empty?
      self.pagamentos.new(:valor => 0)
    end
  end

  def is_delivered?
    self.ativo == VEHICLE_STATUS.index('DELIVERED')
  end

  def ativo?
    ativo != VEHICLE_STATUS.index('DELIVERED')
  end

  def save_current_location
    unless self.cidade_id.nil? || self.estado_id.nil?
      localizacao = "#{Cidade.find(self.cidade_id).text}, #{Estado.find(self.estado_id).sigla}"
      self.update_column(:localizacao, localizacao)
    end
  end

  def if_in_freighter_get_its_location
    if self.cegonha
      self.update_column(:localizacao, self.cegonha.localizacao)
      self.update_column(:cidade_id, self.cegonha.cidade_id)
      self.update_column(:estado_id, self.cegonha.estado_id)
    end
  end

  def remove_car_from_freighter_tracking
    if self.cegonha != Car.find(self.id).cegonha and !Car.find(self.id).cegonha.nil?
      cegonha = Car.find(self.id).cegonha
      cars = Car.find(self.id).cegonha.cars
      cars.delete(self)
      cegonha.tracking.changes.first.update_column(
        :current_cars, cars.map(&:placa).to_sentence
        )
    end
  end

  def add_car_to_freighter_tracking
    if self.cegonha
      self.cegonha.tracking.changes.first.update_column(:current_cars, Car.find(self.id).cegonha.cars.map(&:placa).to_sentence)
    end
  end

  def owner
    self.comprador ? self.comprador : self.empresa
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  before_filter :authenticate_user!

  def index
    # para o sidebar
    @car = Car.find(params[:car_id]) if params[:car_id]
    @cars = Car.order(:data_compra).where("ativo != #{VEHICLE_STATUS.index 'DELIVERED'}")
    @cars.empty? ? @mensagem = "Nenhum Cliente Cadastrado" : @mensagem = "Clientes Ativos"

    @column_class = @car ? 'large-10 columns' : 'large12'

    respond_to do |format|
      format.html
      format.json { render json: @cars }
    end
  end

  def inativos
    # para o sidebar
    @car = Car.find(params[:car_id]) if params[:car_id]
    @column_class = @car ? 'large-10 columns' : 'large12'

    @cars = Car.order(:data_compra).where("ativo = #{VEHICLE_STATUS.index 'DELIVERED'}")
    @cars.empty? ? @mensagem = "Nenhum Cliente Finalizado" : @mensagem = "Clientes Finalizados"

    respond_to do |format|
      format.html
      format.json { render json: @cars }
    end
  end

  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @car }
    end
  end

  def new
    gon.compradores = Comprador.all
    gon.empresas = Empresa.all

    @car = Car.new
    @cegonhas = Cegonha.all
    @parceiros = Parceiro.all
    @status_pagamentos = StatusPagamento.all

    params[:pessoa_juridica] ? @car.build_empresa : @car.build_comprador

    @car.build_debito
    @car.pagamentos.build

    respond_to do |format|
      format.html
      format.json { render json: @car }
    end
  end

  def create
    @car = Car.new(params[:car])
    @status_pagamentos = StatusPagamento.all
    @car.ativo = params[:ativo] unless params[:ativo].nil?

    if @car.comprador
      compradores = Comprador.all
      comprador_existente = compradores.collect{|comprador| if comprador.cpf == @car.comprador.cpf; comprador; end}
      comprador_existente.delete(nil)

      if !comprador_existente.empty?
        @car.comprador = Comprador.find(comprador_existente[0][:id])
        @car.comprador.update_attributes(params[:car][:comprador_attributes])
      end

    elsif @car.empresa
      empresas = Empresa.all
      empresa_existente = empresas.collect{|empresa| if empresa.cnpj == @car.empresa.cnpj; empresa; end}
      empresa_existente.delete(nil)
      if !empresa_existente.empty?
        @car.empresa = Empresa.find(empresa_existente[0][:id])
        @car.empresa.update_attributes(params[:car][:empresa_attributes])
      end
    end

      respond_to do |format|
      if @car.save
        redirect_to edit_car_path(@car, :edit_location => true, :car => @car)  and return if params[:edit_location]
        format.html { redirect_to @car, notice: 'Compra gerada com sucesso' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
      gon.compradores = Comprador.all
      gon.empresas = Empresa.all

      @car = Car.find(params[:id])

      @status_pagamentos = StatusPagamento.all
      @cegonhas = Cegonha.all
      @parceiros = Parceiro.all
  end

  def limited_edit
    @car = Car.find(params[:id])
    @status_pagamentos = StatusPagamento.all

    respond_to do |format|
      if @car.update_attributes(params[:car])
          format.html { redirect_to @car, notice: 'Dados atualizados com sucesso.' }
          format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @car = Car.find(params[:id])
    @car.ativo = params[:ativo] unless params[:ativo].nil?

    # saving car information
    if (params[:save_and_return] || params[:edit_location])
      respond_to do |format|
        if @car.update_attributes(params[:car])
          format.html { redirect_to @car, notice: 'Dados atualizados com sucesso.' } if params[:save_and_return]
          format.html { redirect_to :action => :edit, :car => @car, :edit_location => true, notice: 'Dados atualizados com sucesso.' } if params[:edit_location]
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      end

    # saving location information
    elsif params[:location_saved]
      if !@car.estado_origem.nil?
        @car.cegonha_id = nil
      end
      respond_to do |format|
        if @car.update_attributes(params[:car])
          format.html { redirect_to @car, notice: 'Dados atualizados com sucesso.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  def generate_pdf
    @car = Car.find(params[:id])
    flash[:notice] = "PDF gerado na data #{Time.now.strftime('%d/%m/%Y')}"

    filename = "#{Rails.root}/public/Relatorio_#{@car.placa}_#{Time.now.strftime('%d_%m_%Y')}.pdf"

    html = render_to_string(:template => "/cars/show.pdf.erb", :layout => false,:content_type => "text/html", :charset => "utf-8")
    kit = PDFKit.new(html, :disable_javascript => true )
    kit.stylesheets << "#{Rails.root}/app/assets/to_pdf.css"
    pdf = kit.to_pdf
    file = kit.to_file(filename)

    send_file filename, :type => 'application/pdf'

    #File.delete(filename)
  end
end

app/views/cars/_cars.html.haml
.row
  %div{:class => "#{@column_class}"}
    %table#cars.display{ :cellpading => 0, :cellspacing => 0, :border => 0, :style => "width: 100%;"}
      %thead
        %tr.nowrap
          %th
            Início
          %th
            Placa
          %th
            Modelo
          %th
            Localização Atual
          %th
            Cliente
          %th
            Telefone
          %th
            CPF/CNPJ
          %th{ :style => 'width: 100px;'}
            Frete Total
          %th
            Cegonha 
          %th
            Parceiro 

      %tbody
        - @cars.each_with_index do |car, index|
          -if car.status_pagamento.value == 1
            - @row_class = 'nao-pago'
          - elsif car.status_pagamento.value == 2
            - @row_class = 'pendente'
          - else
            - @row_class = '';
          %tr
            %td{ :class => @row_class }
              = car.data_compra.strftime("%d/%m/%y")
            %td{ :class => "#{@row_class} nowrap" }
              = link_to image_tag("edit_local.png", :border=>0), edit_car_path(car, :car => car.id), :class => 'right'
              = link_to car.placa, :car_id => car.id
            %td{ :class => @row_class }
              = car.modelo.titleize
            %td{ :class =>  @row_class }
              -if car.ativo? 
                = link_to image_tag("edit_local.png", :border=>0, :title => "Editar Localização"), edit_car_path(car, :edit_location => true, :car => car.id), :class => 'right'
              -unless car.localizacao.nil? 
                = car.localizacao
            %td{ :class =>  @row_class }
              = car.comprador ? car.comprador.nome : car.empresa.nome
            %td{ :class =>  @row_class }
              = car.comprador ? car.comprador.telefone : car.empresa.telefone
            %td{ :class =>  @row_class }
              = car.comprador ? car.comprador.cpf : car.empresa.cnpj 
            %td{ :class =>  "#{@row_class} nowrap" }
              = number_to_currency(car.debito.valor_total)
            %td{ :class =>  @row_class }
              = car.cegonha ? link_to(car.cegonha.placa, car.cegonha) : ""
            %td{ :class =>  @row_class }
              = car.parceiro ? link_to(car.parceiro.nome, car.parceiro) : ""

    - if current_user.admin? && !defined?(inativo)
      = link_to 'Novo Cliente (Pessoa Física)', new_car_path, :class => 'button'
      = link_to 'Novo Cliente (Pessoa Jurídica)', {:action => :new, :pessoa_juridica => true}, :class => 'button'

  -if @car
    %div{ :class => "large-2 columns" }
      -if saldo_devedor_do_cliente(@car.comprador ? @car.comprador : @car.empresa) >= 0
        - row_class = 'blue'
      -else
        - row_class = 'red'
      %dl
        %h3
          = @car.placa
        %dt
          Saldo Devedor do Cliente
        %dd{ :class => "#{row_class}" }
          = number_to_currency(saldo_devedor_do_cliente(@car.comprador ? @car.comprador : @car.empresa))
        %dt 
          Localização Atual:
        %dd 
          -unless @car.localizacao.nil? 
            = @car.localizacao
        %dt 
          Cidade de Origem:
        %dd 
          -unless @car.cidade_origem.nil?
            = Cidade.find(@car.cidade_origem).text
            = Estado.find(@car.estado_origem).sigla
        %dt 
          Cidade de Destino:
        %dd 
          -unless @car.cidade_destino.nil?
            = Cidade.find(@car.cidade_destino).text
            = Estado.find(@car.estado_destino).sigla
        %dt 
          Previsão de Entrega:
        %dd 
          = @car.data_prevista.strftime("%d/%m/%Y") unless @car.data_prevista.nil?
        %dt 
          Status do Pagamento
        %dd 
          = @car.status_pagamento.status
        %dt 
          Status do Veículo
        %dd 
          = t(VEHICLE_STATUS[@car.ativo])
        %dt 
          Modelo
        %dd 
          = @car.modelo.titleize
        %ul.button-group.small
          %li
            = link_to "Detalhes", @car, :class => "custom-button-tiny" 
          %li
            = link_to "Editar", edit_car_path(@car), :class => "custom-button-tiny" 
          %li
            = link_to "Deletar", @car, method: :delete, confirm: "Are you sure?", :class => "custom-button-tiny" 

app/views/cars/_editar_localizacao.html.haml
.row
  .large-6.columns.end
    %fieldset
      %legend
        %h5 Dados do Veículo
      = form_for(@car) do |f|
        = f.label :localizacao, "Localização Atual"
        .row
          .large-5.columns
            = f.collection_select :estado_id, Estado.order(:nome), :id, :nome, :include_blank => true
          .large-7.columns
            = f.grouped_collection_select :cidade_id, Estado.order(:nome), :cidades, :nome, :id, :text, include_blank: true

        = f.label :cidade_origem, "Origem do Carro"
        .row
          .large-5.columns
            = f.collection_select :estado_origem, Estado.order(:nome), :id, :nome, :include_blank => true
          .large-7.columns
            = f.grouped_collection_select :cidade_origem, Estado.order(:nome), :cidades, :nome, :id, :text, include_blank: true

        = f.label :cidade_destino, "Destino do Carro"
        .row
          .large-5.columns
            = f.collection_select :estado_destino, Estado.order(:nome), :id, :nome, :include_blank => true
          .large-7.columns
            = f.grouped_collection_select :cidade_destino, Estado.order(:nome), :cidades, :nome, :id, :text, include_blank: true

        - if @car.cegonha and !@car.cidade_origem.nil?
          = f.submit "Salvar", :name => 'location_saved', :class => :button, confirm: "Ao alterar a localização individual do veículo, ele irá automaticamente ser removido da Cegonha #{@car.cegonha.placa}. Para alterar sua localização sem removê-lo da cegonha, atualize a localização diretamente pela cegonha. Deseja alterar a localização e remover o veículo da cegonha mesmo assim?"
        - else
          = f.submit "Salvar", :name => 'location_saved', :class => :button

app/views/cars/_pagamentos.html.haml
%table{ :cellspacing => "0", :summary => "Detalhes do Pagamento", :width => '100%' }
  %caption
    %h4.nowrap Pagamentos do Cliente

  %tr
    %th Data do Pagamento
    %th Valor do Pagamento
    %th Forma de Pagamento

  - car.owner.pagamentos.where("data_pagamento <= ?", Date.today).order("data_pagamento ASC").each do |pagamento|
    - if pagamento.saldo >= 0
      - row_class  = 'blue'
    - else
      - row_class = 'red'

    %tr
      %td= pagamento.data_pagamento.strftime('%d/%m/%Y') unless pagamento.data_pagamento.nil?
      %td= number_to_currency(pagamento.valor)
      %td= pagamento.forma_pagamento

%table{ :cellspacing => "0", :summary => "Detalhes do Pagamento", :width => '100%' }
  %tr
    %th Provisionado Para Dia
    %th Valor Provisionado
    %th Forma de Pagamento

  - car.owner.pagamentos.where("data_pagamento > ?", Date.today).order("data_pagamento ASC").each do |pagamento|
    - if pagamento.saldo >= 0
      - row_class  = 'blue'
    - else
      - row_class = 'red'

    %tr
      %td= pagamento.data_pagamento.strftime('%d/%m/%Y') unless pagamento.data_pagamento.nil?
      %td= number_to_currency(pagamento.valor)
      %td= pagamento.forma_pagamento

app/views/cars/_payments_summary.html.haml
%table{ :cellspacing => "0", :summary => "Resumo do Pagamento", width: '100%' }
  %caption
    %h4.nowrap
      Resumo dos Pagamentos
  %tr
    %th
      Total Pago
      %td
        = number_to_currency(soma_dos_pagamentos_efetuados(car.owner))
  %tr
    %th
      Saldo Devedor
    - if saldo_devedor_do_cliente(car.owner) >= 0
      - @row_class  = 'blue'
    - else
      - @row_class = 'red'

    %td
      %span{ :class => @row_class}
        =  number_to_currency(saldo_devedor_do_cliente(car.owner))
  %tr
    %th
      Provisionados
    - if saldo_devedor_do_cliente(car.owner) >= 0
      - @row_class  = 'red'
    - else
      - @row_class = 'blue'

    %td
      %span{ :class => @row_class }
        = number_to_currency(pagamentos_provisionados(car.owner))
  %tr
    %th
      Taxa de Redespacho
    %td
      = number_to_currency(car.debito.taxa_despacho)

app/views/cars/edit.html.haml
- if !current_user.admin?
  Desculpe, você precisa ter direitos administrativos para visualizar esta página!
- else
  %h1
    Editando Dados

  - if params[:edit_location]
    = render 'editar_localizacao'
  - else
    = render 'form'

app/views/cars/inativos.html.haml
%p
  %h1= @mensagem
- if !@cars.empty?
  = render 'cars', :inativo => true

app/views/cars/index.html.haml
%p
  %h1= @mensagem
-if !@cars.empty?
  = render 'cars'

- elsif current_user.admin?
  = link_to 'Novo Cliente (Pessoa Física)', new_car_path, :class => :button
  = link_to 'Novo Cliente (Pessoa Jurídica)', {:action => :new, :pessoa_juridica => true}, :class => :button

app/views/cars/new.html.haml
%h1
  Novo Cliente

= render 'form'

app/views/cars/show.html.haml
%p.small
  %b= link_to 'GERAR DOCUMENTO PDF', :action => 'generate_pdf', :id => @car.id

.row{ 'data-equalizer' => ""}
  .large-4.columns
    - if @car.comprador
      %table.text-left{ :cellspacing => 0, :summary => "Detalhes do Cliente" , 'data-equalizer-watch' => '', :width => 350}
        %caption
          %h4 Detalhes do Cliente
        %tr
          %th Nome do Cliente
          %td= @car.comprador.nome
        %tr
          %th RG
          %td= @car.comprador.rg
        %tr
          %th CPF
          %td= @car.comprador.cpf
        %tr
          %th Telefone
          %td= @car.comprador.telefone
        %tr
          %th Celular
          %td= @car.comprador.celular
        %tr
          %th E-Mail
          %td= @car.comprador.email
        %tr
          %th Nome de Parente ou Conhecido
          %td= @car.comprador.parente
        %tr
          %th Telefone de Parente ou Conhecido
          %td= @car.comprador.telefone_parente
        %tr
          %th Observação
          %td= @car.comprador.observacao

    - elsif @car.empresa
      %table.text-left{ :cellspacing => 0, :summary => "Detalhes do Cliente" , 'data-equalizer-watch' => '', :width => 350}
        %caption
          %h4
            Detalhes da Empresa
        %tr
          %th Nome da Empresa
          %td= @car.empresa.nome
        %tr
          %th Nome do Contato
          %td= @car.empresa.contato
        %tr
          %th CNPJ
          %td= @car.empresa.cnpj
        %tr
          %th Telefone
          %td= @car.empresa.telefone
        %tr
          %th Celular
          %td= @car.empresa.celular
        %tr
          %th E-Mail
          %td= @car.empresa.email
        %tr
          %th Observação
          %td= @car.empresa.observacao

  .large-4.columns
    %table.text-left{ :cellspacing => "0", :summary => "Detalhes do Carro" , 'data-equalizer-watch' => '', :width => 350}
      %caption
        %h4
          Detalhes do Carro
      %tr
        %th Modelo do Carro
        %td=  @car.modelo
      %tr
        %th Placa
        %td= @car.placa
      - if @car.cegonha
        %tr
          %th Cegonha
          %td= link_to(@car.cegonha.placa, @car.cegonha)
      - elsif @car.parceiro
        %tr
          %th Parceiro
          %td= link_to(@car.parceiro.nome, @car.parceiro)
      %tr
        %th Localização Atual
        %td= @car.localizacao
      - unless @car.cidade_origem.nil? && @car.estado_origem.nil?
        %tr
          %th Origem
          %td
            = "#{Cidade.find(@car.cidade_origem).text}, "
            = Estado.find(@car.estado_origem).sigla
      - unless @car.cidade_origem.nil? && @car.estado_origem.nil?
        %tr
          %th Destino
          %td
            = "#{Cidade.find(@car.cidade_destino).text}, "
            =  Estado.find(@car.estado_destino).sigla
      %tr
        %th Data da Compra
        %td= @car.data_compra.strftime("%d/%m/%Y") unless @car.data_compra.nil?
      %tr
        %th Status do Carro
        %td= t(VEHICLE_STATUS[@car.ativo])
      %tr
        %th Data Prevista da Entrega
        %td= @car.data_prevista.strftime("%d/%m/%Y") unless @car.data_prevista.nil?
      %tr
        %th Observação
        %td= @car.observacao

  .large-4.columns.end
    %table.text-left{ :cellspacing => "0", :summary => "Detalhes do Pagamento", 'data-equalizer-watch' => '', :width => 350 }
      %caption
        %h4
          Detalhes do frete
      %tr
        %th Status do Pagamento do Carro
        %td= @car.status_pagamento.status
      %tr
        %th Valor do Frete
        %td= number_to_currency(@car.debito.valor_frete)
      %tr
        %th Taxa de Plataforma
        %td= number_to_currency(@car.debito.taxa_plataforma)
      %tr
        %th Taxa de Plataforma Origem
        %td= number_to_currency(@car.debito.taxa_plataforma_origem)
      %tr
        %th Taxa de Plataforma Destino
        %td= number_to_currency(@car.debito.taxa_plataforma_destino)
      %tr
        %th Taxa de Balsa
        %td= number_to_currency(@car.debito.taxa_balsa)
      %tr
        %th Desconto
        %td.red= number_to_currency(@car.debito.desconto)
      %tr
        %th Total do Frete
        %td= number_to_currency(@car.debito.valor_total)
      %tr
        %th Observação
        %td= @car.debito.observacao

%hr
.row
  .large-3.columns
    %table{ :cellspacing => "0", :summary => "Carros do Cliente", :width => '100%' }
      %caption
        %h4.nowrap
          Carros do Cliente
      %tr
        %th Placa
        %th Frete
      - @car.owner.cars.each do |car|
        %tr
          %td= car.placa
          %td= number_to_currency(car.debito.valor_total)

  .large-4.columns
    =render 'payments_summary', car: @car
  .large-5.columns
    =render 'pagamentos', car: @car

- if @car.ativo?
  =  link_to 'Editar', edit_car_path(@car), :class => :button
  = link_to 'Voltar', cars_path, :class => :button

app/views/cars/update_city_menu.html.haml
- if @estado.cities.present?
  %select.neighborhood_field{ :name => "search[city_field]"}
  = options_from_collection_for_select(@estado.cidades, :id, :name)