config/routes.rb
Carcontrol::Application.routes.draw do


  resources :contatos

  get "clientes/index"

  # resources :cegonhas
  get "cars/new"
  get "search/index"
  get "cars/inativos"
  get "cars/editar_localizacao"

  resources :compradores
  resources :empresas
  resources :cars do
    get :limited_edit
  end

  resources :cegonhas do
    member do
      get :logistica
      post :logistica_save
    end
  end

  resources :parceiros
  devise_for :users, :path_prefix => "d"
  resources :users
  resources :clientes
  resources :financeiros
  match ":controller(/:action(/:id))(.:format)"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  root :to => 'clientes#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that"s not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ":controller(/:action(/:id))(.:format)"
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      = link_to 'Transeder', root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        Menu
  .top-bar-section
    %ul.right
      = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li.divider
%li
  = link_to "Ativos", cars_path
%li.divider
%li
  %a{:href => "/cars/inativos"}
    Finalizados
%li.divider
%li
  = link_to "Cegonhas", cegonhas_path
%li.divider
%li
  = link_to "Parceiros", parceiros_path
%li.divider
%li
  = link_to "Clientes", compradores_path
%li.divider
%li
  = link_to "Controle Financeiro", financeiros_path
- if user_signed_in?
  %li.divider
  %li
    = link_to('Logout', destroy_user_session_path, :method => :delete)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Transeder'
    = include_gon

    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Transeder'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
    #footer
      %p.small 2012 - 2014 - Akirayoshida Solutions&copy. Powered by <a href='http://www.rubyonrails.org'>Ruby on Rails</a>
      %p.small{'padding-bottom' => 0} Licenciado para Transeder

app/views/layouts/cliente.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Carcontrol'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Carcontrol'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
    #footer
      %p.small 2012 - 2014 - Akirayoshida Solutions&copy. Powered by <a href='http://www.rubyonrails.org'>Ruby on Rails</a>
      %p.small{'padding-bottom' => 0} Licenciado para Transeder